### ISSUE TITLE
django-debug-toolbar support

### ISSUE THREAD

**Issue by frague59** [rkhleics/wagtailmenus#115]
Hi, 

I've an error on my dev platform : I'm using dhango-debug-toolbar on it, and I've a blocking issue :

```
TypeError at /

get_version() takes exactly 1 argument (0 given)

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/
Django Version: 	1.10.6
Exception Type: 	TypeError
Exception Value: 	

get_version() takes exactly 1 argument (0 given)

Exception Location: 	/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/local/lib/python2.7/site-packages/debug_toolbar/panels/versions.py in get_app_version, line 47
Python Executable: 	/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/bin/python
Python Version: 	2.7.12
Python Path: 	

['/var/www/intranet.tourcoing.fr/src',
 '/var/www/intranet.tourcoing.fr/lib',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/intranet_wagtail/src',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/intranet_wagtail',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/django-restaurant-menu',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/django-wagtailadmin-ajax-field',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/django-fontawesome',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/django-buttons',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/intranet_wagtail/src',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/wagtailpolls',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/lib-tk',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/lib-old',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/local/lib/python2.7/site-packages',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages',
 '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/intranet_wagtail/src']

Server time: 	Ven, 10 Mar 2017 09:53:56 +0100
```
... 
```
/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/local/lib/python2.7/site-packages/debug_toolbar/panels/versions.py in get_app_version

                    version = get_version()

     ...

▼ Local vars
Variable 	Value
app 	

<module 'wagtailmenus' from '/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/local/lib/python2.7/site-packages/wagtailmenus/__init__.pyc'>

get_version 	

<function get_version at 0x7f3bc156b398>

self 	

<debug_toolbar.panels.versions.VersionsPanel object at 0x7f3bbb6a5bd0>
```
This issue is about the signature of the get_version() function in wagtailmenus, which needs a version as argument, but is not supported by django-debug-toolbar.

Thanks for this great menu !

**Comment by frague59** [comment]
Full stacktrace : 
```
Traceback (most recent call last):
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self.handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 234, in handle_uncaught_exception
    return handle_uncaught_exception(request, resolver, exc_info)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 136, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 129, in process_response
    panel.generate_stats(request, response)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/debug_toolbar/panels/versions.py", line 29, in generate_stats
    versions += list(self.gen_app_versions())
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/debug_toolbar/panels/versions.py", line 39, in gen_app_versions
    version = self.get_app_version(app)
  File "/home/fguerin/Boulot/workspace/projects/intranet.ville.tg/virtualenv/lib/python2.7/site-packages/debug_toolbar/panels/versions.py", line 47, in get_app_version
    version = get_version()
TypeError: get_version() takes exactly 1 argument (0 given)
```

**Comment by ababic** [comment]
Sorry, @frague59. I don't know anything about django-debug-toolbar or how it searches for versions for things, and wagtailmenus is only really concerned with compatibility with django and wagtail... guaranteeing compatibility with other apps developers might happen to be using is something I can't realistically support.

**Comment by ababic** [comment]
For reference, if you look at the following files for Wagtail, you'll see there is a pretty much identical setup for version control. So, I can imagine `wagtailmenus` probably isn't the only thing you'll run into compatibility issues with.

- https://github.com/wagtail/wagtail/blob/master/wagtail/__init__.py
- https://github.com/wagtail/wagtail/blob/master/wagtail/utils/version.py

**Comment by ababic** [comment]
@frague59 As a workaround, you could ttry sub-classing `debug_toolbar.panels.version.VersionsPanel` in your own project and overriding the [`get_app_version()`](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/panels/versions.py#L43) method to prefer the `__version__` attribute over `get_version` methods. But, that might possibly cause issues with other apps.
