### ISSUE TITLE
Cannot migrate with Docker install

### ISSUE THREAD

**Issue by pimarc** [rkhleics/wagtailmenus#356]
Hello,

I have installed wagtail with docker. Everithing works fine but wagtailmenus is not working. When doing the migration, here is console output:

imac-1:wagtest pierre$ docker-compose run web ./manage.py migrate wagtailmenus
Starting wagtest_postgres_1      ... done
Starting wagtest_elasticsearch_1 ... done
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wagtailmenus'

Everything works fine with a local install using the same versions of django (2.2.9) and wagtail (2.7.1).
The base.py is correctly set following your documentation.

Thanks for your help

**Comment by pimarc** [comment]
Sorry

I found myself my mistake

I was running "docker-compose run" instead of "docker-compose exec"
for install and migration.

So everything is working now

Thanks for this nice appli
