### ISSUE TITLE
HTTP 500: 'dict' object is not callable

### ISSUE THREAD

**Issue by demonshreder** [rkhleics/wagtailmenus#361]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:4500/

Django Version: 3.0.4
Python Version: 3.8.2
Installed Applications:
['home',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.core.middleware.SiteMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'wagtailmenus.context_processors.wagtailmenus']

Traceback (most recent call last):
  File "/home/demonshreder/Projects/IFP/wagtail/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)

Exception Type: TypeError at /
Exception Value: 'dict' object is not callable

**Comment by ababic** [comment]
@demonshreder Can you please post the full stack-trace, as the part you've added gives no indication at all to what the problem is.

**Comment by gavin-hutchinson** [comment]
Hi I'm having the same issue as @demonshreder - this occurs when trying to access the admin url.
At first I thought it was a compatibility issue so I tried a range of different django, wagtail, python, and wagtailmenus versions but no luck.

My intial versions -
docker image built from python:3.8-slim
django>=3.0,<3.1
wagtail>=2.8,<2.9
wagtailmenus>=3.0.1

This is the traceback with DEBUG_PROPAGATE_EXCEPTIONS = True.

`[2020-04-24 09:11:01 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-04-24 09:11:01 +0000] [1] [INFO] Listening at: https://0.0.0.0:8000 (1)
[2020-04-24 09:11:01 +0000] [1] [INFO] Using worker: sync
[2020-04-24 09:11:01 +0000] [40] [INFO] Booting worker with pid: 40
[2020-04-24 09:11:01 +0000] [41] [INFO] Booting worker with pid: 41
[2020-04-24 09:11:01 +0000] [42] [INFO] Booting worker with pid: 42
(0.008) SELECT "wagtailcore_site"."id", "wagtailcore_site"."hostname", "wagtailcore_site"."port", "wagtailcore_site"."site_name", "wagtailcore_site"."root_page_id", "wagtailcore_site"."is_default_site", CASE WHEN ("wagtailcore_site"."hostname" = 'sandbox' AND "wagtailcore_site"."port" = 8000) THEN 0 WHEN ("wagtailcore_site"."hostname" = 'sandbox' AND "wagtailcore_site"."is_default_site" = true) THEN 1 WHEN "wagtailcore_site"."is_default_site" = true THEN 2 ELSE 3 END AS "match", "wagtailcore_page"."id", "wagtailcore_page"."path", "wagtailcore_page"."depth", "wagtailcore_page"."numchild", "wagtailcore_page"."title", "wagtailcore_page"."draft_title", "wagtailcore_page"."slug", "wagtailcore_page"."content_type_id", "wagtailcore_page"."live", "wagtailcore_page"."has_unpublished_changes", "wagtailcore_page"."url_path", "wagtailcore_page"."owner_id", "wagtailcore_page"."seo_title", "wagtailcore_page"."show_in_menus", "wagtailcore_page"."search_description", "wagtailcore_page"."go_live_at", "wagtailcore_page"."expire_at", "wagtailcore_page"."expired", "wagtailcore_page"."locked", "wagtailcore_page"."locked_at", "wagtailcore_page"."locked_by_id", "wagtailcore_page"."first_published_at", "wagtailcore_page"."last_published_at", "wagtailcore_page"."latest_revision_created_at", "wagtailcore_page"."live_revision_id" FROM "wagtailcore_site" INNER JOIN "wagtailcore_page" ON ("wagtailcore_site"."root_page_id" = "wagtailcore_page"."id") WHERE ("wagtailcore_site"."hostname" = 'sandbox' OR "wagtailcore_site"."is_default_site" = true) ORDER BY "match" ASC; args=('sandbox', 8000, 0, 'sandbox', True, 1, True, 2, 3, 'sandbox', True)
[2020-04-24 12:31:10 +0300] [42] [ERROR] Error handling request /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'dict' object is not callable
`

**Comment by ababic** [comment]
@gavin-hutchinson What other Django apps do you have installed? Maybe django-debug-toolbar?

**Comment by gavin-hutchinson** [comment]
At this point I've only got one custom app and a few packages.

requirements.txt

django>=2.1.6,<3.0
django-secure==1.0.2

wagtail>=2.8,<2.9
wagtailfontawesome>=1.1.3,<1.2
wagtailstreamforms>=3.9.0
#wagtailmenus>=3.0.1

puput>=1.0,<2.0
django-colorful==1.3.0
django-el-pagination==3.3.0
django-social-share==1.4.0

base.py
INSTALLED_APPS = [
    'apps',

    'wagtail.admin',
    'wagtail.api.v2',
    'wagtail.core',
    'wagtail.documents',
    'wagtail.embeds',
    'wagtail.images',
    'wagtail.search',
    'wagtail.sites',
    'wagtail.snippets',
    'wagtail.users',
    'wagtail.contrib.forms',
    'wagtail.contrib.modeladmin',
    'wagtail.contrib.postgres_search',
    'wagtail.contrib.redirects',
    'wagtail.contrib.routable_page',
    'wagtail.contrib.search_promotions',
    
    #'wagtailmenus',
    'wagtailstreamforms',
    'wagtailfontawesome',
    'modelcluster',
    'rest_framework',
    'taggit',
    'colorful',
    'django_social_share',
    'puput',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
]

**Comment by ababic** [comment]
@gavin-hutchinson Puput is not compatible with Django 3 yet, so that's likely to cause you problems. https://github.com/APSL/puput/blob/master/setup.py#L43

The entire test suite runs against Django 3.0 and Wagtail 2.8 without any errors/failures (which includes fronte-end and back-end view tests), so it's not looking too likely that wagtailmenus is the cause of the problem: https://travis-ci.org/github/rkhleics/wagtailmenus/jobs/647678468

**Comment by gavin-hutchinson** [comment]
@ababic Thanks for the followup I have since removed Puput from the project I was working on although I know Puput was working before wagtailmenus. Puput does have problems with Django 3.0 but I was using less than 3.0 here, django>=2.1.6,<3.0

Anyways I would still like to use wagtailmenus at a later point and when I do I will confirm what happens without Puput.

**Comment by ababic** [comment]
@demonshreder, I just noticed that you have added the context processor to your `MIDDLWARE` setting, instead of updating `TEMPLATES` as described in the [installation instructions] (https://wagtailmenus.readthedocs.io/en/stable/installation.html#installing-wagtailmenus)

**Comment by Bhushan0101** [comment]
this thread is great , and helped me too!!
